### ISSUE TITLE
Please, can you help me please ? 

### ISSUE THREAD

**Issue by bateria2x100** [nathanIL/openiban#1]
I have this repository running on Pythonista, when IBAN is ok, works like a charm, but if it s wrong, is not printing the error.... 

The test code :  
```
from openibanlib import openiban
# By trying to initialize an IBAN object

try:
        openiban.IBAN('DE89370400440532013004')
        print("valid IBAN ")
except IBANFormatValidationException:
        print("Invalid IBAN provided")
```
The error : 
It throwns this : 

_Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/70EF7C81-4506-4E0F-A08E-B2C9E8144F15/Pythonista3/Documents/ibanTest.py", line 5, in <module>
    openiban.IBAN('DE89370400440532013004')
  File "/private/var/mobile/Containers/Shared/AppGroup/70EF7C81-4506-4E0F-A08E-B2C9E8144F15/Pythonista3/Documents/site-packages/openibanlib/openiban.py", line 24, in __init__
openibanlib.exceptions.IBANFormatValidationException: Invalid IBAN format provided: DE89370400440532013004

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/70EF7C81-4506-4E0F-A08E-B2C9E8144F15/Pythonista3/Documents/ibanTest.py", line 7, in <module>
    except IBANFormatValidationException:
**NameError: name 'IBANFormatValidationException' is not defined_**

I ve OpenIban on Python Modules-> site-packages-> openiban, and the exceptions.py has IBANFormatValidationException defined.... 

I m not  a pro developer... so this error is killing me...any help please ? 

Thanks in advance

**Comment by nathanIL** [comment]
@bateria2x100 

few years later, so i guess this isnt relevant anymore.
in case some one runs into this issue, let me know and i will fix.
